### PR TITLE
feat: add filtering ability

### PR DESCRIPTION
**Pull request by Priyanshu44**
Add filtering ability #1891

image

### CODE REVIEW

**Review by jmbuss — CHANGES_REQUESTED** [review]
Can we add some basic tests for these changes?

**Review by corteggiano — APPROVED** [review]

**Comment by corteggiano** [comment]
will approve once merge conflicts are fixed!

**Comment by Priyanshu44** [comment]
> will approve once merge conflicts are fixed!

Resolved

**Comment by tracy-french** [comment]
@Priyanshu44 It looks like we need to fix more merge conflicts. Sorry about that! Could you resolve those and we will merge ASAP?

**Comment by Priyanshu44** [comment]
Conflict resolved.

**Pull request merged**
