### PR TITLE
docs: create doc site [code from this has been merged ]

### PR DESCRIPTION
**Pull request by diehbria**
## UPDATE 
I have updated this with new documentation, have retained all the changes in packages from before. 

## Overview
Sets up a docsite via storybook which will automatically deploy on push to main.

An example of what this deploys can be seen at https://awslabs.github.io/iot-app-kit/?path=/docs/components-line-chart--docs

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

**Review by corteggiano — DISMISSED** [review]

**Comment by tracy-french** [comment]
What's the state of this PR?

**Comment by diehbria** [comment]
> What's the state of this PR?

The PR would be good to merge with the exception of storybook failing to build when `VideoPlayer` is exported from react-components due to video.js overriding `global.window`. see https://github.com/videojs/video.js/issues/5680

**Comment by tracy-french** [comment]
Do we good with doing that? Or should this PR be set as a draft until the change is made?

**Comment by diehbria** [comment]
> Are we good with doing that? Or should this PR be set as a draft until the change is made?

No - marked as draft

**Review by chejimmy — DISMISSED** [review]
📄 LGTM 🚀

**Pull request closed without merging**
