### PR TITLE
Unsubscribe bug

### PR DESCRIPTION
**Pull request by jebek**
## Overview
There is an unsubscribe bug where components aren't getting unsubscribed. You can see this by creating a `KPI` component, then deleting, and you still see network requests for data.

I believe this bug also affects react-components when it tries to unsubscribe an `id` that isn't in the `subscriptions`. If you try to create a `Status` component, you will get an error saying the `requested subscription does not exist`.

Screen Shot 2023-01-31 at 12 19 37 PM

I use yalc link here because npm link wasn't quite working for me. In `react-components`, (1) `npm run build`, (2) `yalc publish`. then in the `dashboard` package, (1) `yalc add "@iot-app-kit/react-components"` , (2) `npm run start`

### Scene Composer
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to complete below.

- Click on the workflow details
- Select the Summary item on the left
- Download the zip file

To run the storybook build locally, you need a local static web server:

```
npm install -g httpserver
cd <Extracted Zip Directory>
httpserver
```

Then open the website http://localhost:8080 to run the doc site.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

**Comment by boweihan** [comment]
@jebek is the fix for this bug in this code change? can it be committed separately from the components migration? easier to review that way

**Comment by jebek** [comment]
@boweihan yea for sure. This is just a draft PR to possibly get some feedback for the current unsubscribe bug from Brian. It won't be converted to a PR. So the status/KPI component PR will be separate.

**Review by diehbria — COMMENTED** [review]
I'd love to see the ease of use get to the point where a component could be as simple as 

```
import { useTimeSeriesData } from '@iot-app-kit/react-components';

const LineChart = ({ queries, viewport: passedInViewport }) => {
  const { datastreams, viewport } = useTimeSeriesData({ 
    queries,
    viewport: passedInViewport
  })
  
  return (
    <LineChart 
      datastream={datastreams} 
      viewport={viewport} 
    />
  )
}
```

and optionally with the full set of configurations:
```
import { useTimeSeriesData } from '@iot-app-kit/react-components';

const LineChart = ({ queries, viewport: passedInViewport, annotations, stylesettings }) => {
  const { datastreams, annotations, viewport, updateViewport } = useTimeSeriesData({ 
    queries,
    supportedDataTypes: ['NUMBER'],
    assignDefaultColors,
    styleSettings,
    annotations,
    viewport: passedInViewport,
    requestSettings: {
      fetchFromStartToEnd: true
    }
  })
  
  return (
    <LineChart 
      updateViewport={updateViewport} 
      datastream={datastreams} 
      viewport={viewport} 
      annotations={annotations}
    />
  )
}
```

**Comment by diehbria** [comment]
being handled in different PR

**Pull request closed without merging**
