### PR TITLE
fix(dashboard): update type path in package json

### PR DESCRIPTION
**Pull request by jmbuss**
## Overview
update type path in package json.

This will allow typescript packages to find the correct types file for dashboard.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

**Comment by tracy-french** [comment]
What's the expected outcome of this change?

**Comment by jmbuss** [comment]
> What's the expected outcome of this change?

will allow types to be discoverable by typescript packages that consume it.

**Comment by tracy-french** [comment]
> > What's the expected outcome of this change?
> 
> will allow types to be discoverable by typescript packages that consume it.

Cool! That's what I thought, but just wanted to confirm!

**Review by tracy-french — APPROVED** [review]
Thank you for completing this! Ship it!

**Pull request merged**
